### ISSUE TITLE
Пагинатор

### ISSUE THREAD

**Issue by apazhe** [ilvar/apachan#19]
Переключаемый (через меню "настройки").

1. "Хардкор" - все комменты на одной странице
2. "Олдскул" - обычная пагинация (с обратной нумерацией страниц - 5 4 3 2 1)
3. "Ещё! Ещё!" - Под первыми пятьюдесятью комментами кнопка "ещё!", догружающая в страницу ещё пятьдесят комментов и т.д.

**Comment by ilvar** [comment]
Насколько это необходимо? Я предвижу гемор с "хардокром" в постах с 10к+ комментов.

**Comment by apazhe** [comment]
Сделай просто второй вариант и хватит.

**Comment by ilvar** [comment]
Done
