### ISSUE TITLE
Проверка уникальности поста учитывает неотправившиеся посты (?).

### ISSUE THREAD

**Issue by apazhe** [ilvar/apachan#29]
http://apachan.net/picXltbzwIdxA7M.html

**Comment by ilvar** [comment]
По поведению похоже на наш "анти-ддос" http://nginx.org/en/docs/http/ngx_http_limit_req_module.html

Попробуем расслабить.

**Comment by ilvar** [comment]
расслаблено, должно стать лучше https://github.com/ilvar/apachan/commit/9ee32a8963da2ac4f4385a38060e0369b2c2ee96
