### ISSUE TITLE
Https://

### ISSUE THREAD

**Issue by apazhe** [ilvar/apachan#30]
Редирект на https версии сайтов, как бы на них не заходили.

**Comment by apazhe** [comment]
also очень не повредили бы сквозные куки на всех доменах и http: https:

**Comment by ilvar** [comment]
С куками все непросто, браузеры не дают ставить куки на сторонние домены, т.е. надо в нашем случае человека с org редиректить на net с некоей секьюрной подписью, чтобы net поставил себе куку и средиректил обратно. Или наоборот - если я захожу на net, и там нет куки - идет редирект на org с вопросом "кука е?".

Если такое надо - ебашь тикет.
