### ISSUE TITLE
Изменения в разделах.

### ISSUE THREAD

**Issue by apazhe** [ilvar/apachan#37]
- Общий
- Вконтакте
- Request
- Медиа
 
Содержимое сливается в "Бред", разделы уничтожаются за малопопулярностью.

- Гей-гетто
- Есть Одна Тян

Объединяются в раздел "сексофилия" (/sex/), разделы уничтожаются.

- Ня-Ня
- Программирование

Остаются без изменений.

- Политота

Новый раздел: 

"мусор" (/trash/) - помещённые или перемещённые в него посты уничтожаются через сутки после помещения/перемещения.

**Comment by ilvar** [comment]
вынес мусор, остальное готово
