### ISSUE TITLE
мусор

### ISSUE THREAD

**Issue by ilvar** [ilvar/apachan#38]
"мусор" (/trash/) - помещённые или перемещённые в него посты уничтожаются через сутки после помещения/перемещения.

**Comment by apazhe** [comment]
не работает удаление через сутки

**Comment by ilvar** [comment]
А эти посты туда модератором перенесены или исходно добавлены в мусор?

**Comment by apazhe** [comment]
модератором переносятся

но наверняка какие-то упоротые будут и сами создавать

так что предлагаю сделать так: 

1. Пост оказался в "мусоре" (перенесён модератором, создан, слили мочеванием).
2. Ждём сутки.
3. Далее если в течение ста минут у поста не появляется новых комментов - пост удаляется. Можно выводить в статус время до удаления.

**Comment by ilvar** [comment]
Done
